owner: boarda
repo: boarda-status
user-agent: boarda

sites:
  - name: Studio
    url: https://beta.studio.boarda.io
    slug: studio
  - name: Account
    url: https://account.boarda.io
    slug: account
  - name: Developers
    url: https://developers.boarda.io
    slug: developers
  - name: Cast
    url: https://cast.boarda.io/api/health
    slug: cast
  - name: API Gateway
    url: https://api.boarda.io/_health
    slug: api-gateway
  - name: Website
    url: https://boarda.io
    slug: website

status-website:
  cname: status.boarda.io
  name: Boarda Status
  logoUrl: https://raw.githubusercontent.com/boarda/boarda-status/main/assets/icon.svg
  favicon: https://raw.githubusercontent.com/boarda/boarda-status/main/assets/favicon.ico
  theme: light
  themeUrl: https://raw.githubusercontent.com/boarda/boarda-status/main/assets/boarda-theme.css
  navbar:
    - title: Status
      href: /
    - title: boarda.io
      href: https://boarda.io
  scripts:
    - src: https://raw.githubusercontent.com/boarda/boarda-status/main/assets/theme-toggle.js

i18n:
  footer: "© Boarda. All rights reserved. Powered by Upptime."
